---
- name: Create an ubuntu container and mount /data as a volume
  hosts: all
  tasks:
    - name: Create ubuntu container
      docker_container:
        name: myubuntu
        image: ubuntu
        interactive: true
        tty: true
        volumes:
          - /data
