---
- name: Implementing docker compose using ansible
  hosts: all
  tasks:
    - name: Create mysql container
      docker_container:
        image: mysql:5
        name: mydb
        env:
         MYSQL_ROOT_PASSWORD: intelliqit

    - name: Create a wordpress container
      docker_container:
        image: wordpress
        name: mywordpress
        links:
          - mydb:mysql
        ports:
          - 8888:80
...
