---
- name: Install apache2/httpd on Ubuntu and Redhat servers
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on RHEL servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "Welcome to IntelliQIt"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check if apache2/httpd is responding
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.6.25
        - http://172.31.29.134
        - http://172.31.23.5
...








