---
- name: Check if a file is executable if so delete it
  hosts: all
  tasks:
    - name: Check for file info
      stat:
        path: /tmp/file1
      register: results
    - name: Display output of the  above module
      debug:
        var: results
    - name: Delete file if it is executable
      file:
        name: /tmp/file1
        state: absent
      when: results.stat.executable == true
