---
- name: Install/uninstalltion/upgradation s/w applications
  hosts: all
  tasks:
    - name: Working on s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: latest,c: yes}
...



